# Generated by Django 3.2.4 on 2021-06-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talk',
            old_name='price',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='description',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='name',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='quantity',
        ),
        migrations.AddField(
            model_name='talk',
            name='first_name',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='talk',
            name='last_name',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='talk',
            name='speaker',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='talk',
            name='venue',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='talk',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
